### ISSUE TITLE
Import existing pdf to use as template (ideally multiple pages)

### ISSUE THREAD

**Issue by joshpauline** [go-pdf/fpdf#19]
Could you give an example of how we can import an existing pdf to add extra data to it. 

e.g. I would like to import a document and add signatures to it based on signature input images and x,y,w,h location

**Comment by sbinet** [comment]
`go-pdf/fpdf` doesn't have (yet?) facilities to *read* PDFs.

AFAIK, the best library right now to do that is:
- https://pkg.go.dev/rsc.io/pdf
or:
- https://pkg.go.dev/github.com/andybalholm/giopdf/pdf

**Comment by joshpauline** [comment]
@sbinet thank you for letting me know, I will have a look at those libraries!
