### ISSUE TITLE
Latin é output as Ã©

### ISSUE THREAD

**Issue by ingfdoaguirre** [go-pdf/fpdf#23]
Hi, when I write text to a pdf page with accents like "é" the writer outputs as "Ã©" 

I searched why this was happening, and I found that was a encoding problem.
https://www.i18nqa.com/debug/utf8-debug.html

I treid changin the font to "times" "courier" "helvetica" and the problem was persistent.

Can you help me with this problem please.

An image and the test pdf
![2022-06-20_13-18](https://user-images.githubusercontent.com/19358221/174672659-185e730c-91b5-479e-8606-d74a674cc939.png)
[hello.pdf](https://github.com/go-pdf/fpdf/files/8943461/hello.pdf)

**Comment by sbinet** [comment]
does this help?

https://pkg.go.dev/github.com/go-pdf/fpdf#example-Fpdf.CellFormat-Codepage

(otherwise, please provide a minimal program reproducing the issue, thanks)

**Comment by nenodias** [comment]
@sbinet Thanks for the reply.
Solved my problem.
Before:
``` main.go
package main

import (
	"github.com/go-pdf/fpdf"
)

func main() {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(40, 10, "Olá, mundo")
	err := pdf.OutputFileAndClose("hello.pdf")
	if err != nil {
		panic(err.Error())
	}
}
```
![image](https://user-images.githubusercontent.com/3880625/187815551-5c7bbcf5-43db-450b-a13f-a67e3512bc8d.png)

After using the function returned by pdf.UnicodeTranslatorFromDescriptor
```main.go
package main

import (
	"github.com/go-pdf/fpdf"
)

func main() {
	pdf := fpdf.New("P", "mm", "A4", "")
	tr := pdf.UnicodeTranslatorFromDescriptor("")
	pdf.AddPage()
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(40, 10, tr("Olá, mundo"))
	err := pdf.OutputFileAndClose("hello.pdf")
	if err != nil {
		panic(err.Error())
	}
}

```
![image](https://user-images.githubusercontent.com/3880625/187815412-c5cddc92-7951-4f9b-a4d6-63d4b54c449f.png)

**Comment by sbinet** [comment]
glad I could help :)
