### ISSUE TITLE
Euro Icon for CellFormat

### ISSUE THREAD

**Issue by KarlChow92** [go-pdf/fpdf#61]
Hello! I am trying to use the euro icon `€` or `\u20ac` in `CellFormat`, however, I am not getting any success. 

After passing `pdf.CellFormat(w[4], 8, "€[1500,00]", "", 0, "R", false, 0, "")`  I am getting: 
![image](https://github.com/go-pdf/fpdf/assets/2989224/67369920-67f3-4914-aa05-585486a374a5)

Same happens if I put instead of the `€`, `\u20ac`. Can I get some guidance on this please?

**Comment by sbinet** [comment]
UTF-8 handling is a bit cumbersome.
see:
https://pkg.go.dev/github.com/go-pdf/fpdf#example-Fpdf.CellFormat-Codepage

**Comment by sbinet** [comment]
(closing. feel free to reopen if that didn't answer your question)
