### ISSUE TITLE
Load image from byte slice into PDF

### ISSUE THREAD

**Issue by lordofscripts** [go-pdf/fpdf#65]
My document source is a JSON file and, among other things, I extract images that are _Base64_ encoded.

However, I am trying to get that extracted image into PDF but there is no `ImageOptions` that takes a `[]byte` instead of a filename.

**Comment by sbinet** [comment]
couldn't you use `fpdf.(*Fpdf).RegisterImageOptionsReader(...)` with the `io.Reader` wrapping your `[]byte` ?
- https://pkg.go.dev/github.com/go-pdf/fpdf#Fpdf.RegisterImageOptionsReader

_e.g._:
```go
   var img []byte = ...
   typ := doc.RegisterImageOptionsReader("img-name", opts, bytes.NewReader(img))
```
